# Default initial positions for my_robot's ros2_control fake system

initial_positions:
  elbow_joint: 0
  shoulder_pitch_joint: 0
  shoulder_roll_joint: 0
  shoulder_yaw_joint: 0
  wrist_pitch_joint: 0
  wrist_roll_joint: 0
  wrist_yaw_joint: 0