controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - shoulder_roll_joint
      - elbow_joint
      - wrist_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true

