services:
  ros2:
    build: .
    container_name: poc_arm_container

    network_mode: host
    privileged: true 
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0    

    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - poc_arm_build:/ros2_ws/build
      - poc_arm_install:/ros2_ws/install
      - poc_arm_log:/ros2_ws/log

    environment:
      - DISPLAY=${DISPLAY}

    stdin_open: true
    tty: true

    command: bash

volumes:
  poc_arm_build:
  poc_arm_install:
  poc_arm_log:
