# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - shoulder_roll_joint
      - elbow_joint
      - wrist_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true      
