default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  shoulder_yaw_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  shoulder_roll_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  shoulder_pitch_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  elbow_pitch_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  wrist_pitch_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  wrist_roll_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  wrist_yaw_joint:
    has_position_limits: true
    min_position: -3.14
    max_position:  3.14
    has_velocity_limits: true
    max_velocity:  4.7
    has_acceleration_limits: true
    max_acceleration: 8.0

